// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"math"
)

type bang struct{}

func main() {
	basenfft := 3600 * 2
	nfft2 := 16384
	s1 := map[float64]bang{}
	s2 := map[float64]bang{}
	sizes := map[float64]bang{}
	for n := basenfft / 2; n <= basenfft*2; n++ {
		s1[float64(basenfft)/float64(NearestNfft(n))] = bang{}
	}
	for m := nfft2 / 2; m <= nfft2*2; m++ {
		s2[float64(nfft2)/float64(NearestNfft(m))] = bang{}
	}
	for a := range s1 {
		for b := range s2 {
			sizes[a*b] = bang{}
		}
	}
	for s := range sizes {
		fmt.Println(math.Log2(s) * 12)
	}
}

// NearestNfft quantizes nfft to the nearest value supported by PFFFT.
func NearestNfft(nfft int) int {
	// SLOP: generated by free ChatGPT with minimal edits.
	if nfft < 32 {
		return 32
	}

	q := int(4)
	nfft = ((nfft + q - 1) / q) * q
	best := 0
	q = 2 * q * q // pffft.c:1249

	for p2 := 1; p2 <= nfft*10; p2 *= 2 {
		for p3 := p2; p3 <= nfft*10; p3 *= 3 {
			for p5 := p3; p5 <= nfft*10; p5 *= 5 {
				if p5 >= nfft && p5%q == 0 {
					if best == 0 || p5 < best {
						best = p5
					}
				}
				if p5 > nfft*10/5 {
					break
				}
			}
			if p3 > nfft*10/3 {
				break
			}
		}
		if p2 > nfft*10/2 {
			break
		}
	}

	return best
}
